### PR TITLE
Belangrijke wijziging

### PR DESCRIPTION
**Pull request by Mosterdt**
Dit is een zeer nodige toevoeging!

### CODE REVIEW

**Comment by anthonyclays** [comment]
Please add documentation before submitting pull requests.

**Comment by Mosterdt** [comment]
The code is clearly documented underneath the addition. I don't know how long you have been programming, (I guess not for long), because the code is pretty self-explanatory. I think you are just discriminating me you scum cis white male.

**Comment by anthonyclays** [comment]
Your comment to code ratio is less than 42, which is an unforgivable sin when coding a Java project. On top of that you have not written any tests whatsoever. I'm sorry, but I cannot allow unstable code in my project. Please fix the aforementioned issues and I would be happing to review your PR.

**Comment by Mosterdt** [comment]
The addition I did wasn't even in a Java file. There is no point in writing long documentation for a git-file. I tested this well-formed piece of code numerous times on my devices and can assure you everything works as intended. The only unstable thing in this project is you.

**Comment by anthonyclays** [comment]
closed for being derogatory and discriminatory towards Jews

**Comment by Mosterdt** [comment]
I knew it

**Pull request closed without merging**
